name: Bump Version

on:
  push:
    branches: [main]


jobs:
  find_version:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸš› Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: ğŸ” Determine next version type
      id: version_type
      run: |
        TYPE=$(python ./tools/ci_tools.py --bump)
        echo ::set-output name=type::$TYPE

    - name: ğŸ’‰ Inject new version into files
      id: version
      if: steps.version_type.outputs.type != 'skip'
      run: |
        result=$(python ./tools/ci_tools.py --nightly)

        echo ::set-output name=next_tag::${result[0]}

    - name: "âœï¸ Generate full changelog"
      if: steps.version_type.outputs.type != 'skip'
      id: generate-full-changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        breakingLabel: '#### ğŸ’¥ Breaking'
        enhancementLabel: '#### ğŸš€ Enhancements'
        bugsLabel: '#### ğŸ› Bug fixes'
        deprecatedLabel: '#### âš ï¸ Deprecations'
        addSections: '{"documentation":{"prefix":"### ğŸ“– Documentation","labels":["documentation"]},"tests":{"prefix":"### âœ… Testing","labels":["tests"]}}'
        issues: false
        issuesWoLabels: false
        pullRequests: true
        prWoLabels: false
        author: false
        unreleased: true
        compareLink: true
        stripGeneratorNotice: true
        verbose: true
        excludeTagsRegex: "nightly/.+"
        releaseBranch: "main"

    - name: "ğŸ–¨ï¸ Print changelog to console"
      run: cat CHANGELOG.md

    - name: ğŸ’¾ Commit changes
      id: git_commit
      if: steps.version_type.outputs.type != 'skip'
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "[Automated] Bump version"
        git push
        
        echo ::set-output name=sha::$(git rev-parse HEAD)

    - name: ğŸ”¨ Merge main back to develop    
      uses: everlytic/branch-merge@1.1.0
      if: steps.version_type.outputs.type != 'skip'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_ref: 'main'
        target_branch: 'develop'
        commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'

    - name: ğŸš€ Tag and Release
      uses: pypeclub/semver-release-action@master
      if: steps.version_type.outputs.type != 'skip'
      with:
        prefix: nightly/
        bump: ${{ steps.next_version.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.git_commit.outputs.sha }}