name: Bump Version

on:
  push:
    branches: [main]


jobs:
  find_version:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸš› Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: ðŸ”Ž Determine next version type
      id: version_type
      run: |
        git log $(git describe --tags --abbrev=0)..HEAD --merges --oneline > new-in-this-release.log
        TYPE=$(python ./tools/ci_tools.py --logfile new-in-this-release.log)
        rm new-in-this-release.log

        echo ::set-output name=type::$TYPE

    - name: âž• Calculate next version
      id: next_version
      if: steps.version_type.outputs.type != 'skip'
      uses: pypeclub/semver-release-action@master
      with:
        prefix: nightly/
        dry_run: true
        bump: ${{ steps.version_type.outputs.type }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: ðŸ’‰ Inject new version into files
      if: steps.version_type.outputs.type != 'skip'
      run: python ./tools/ci_tools.py --version $VERSION

    - name: Generate Changelog
      if: steps.version_type.outputs.type != 'skip'
      uses: heinrichreimer/github-changelog-generator-action@v2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        user: pypeclub
        project: ci-testing
        futureRelease: $VERSION
        excludeTagsRegex: nightly/.+
        unreleased: true
        releaseBranch: main
        issues: false
        enhancementLabel: "**Enhancements:**"
        author: false

    - name: ðŸ’¾ Commit changes
      id: git_commit
      if: steps.version_type.outputs.type != 'skip'
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "[Automated] Bump version"
        git push
        
        echo ::set-output name=sha::$(git rev-parse HEAD)

    - name: ðŸ”¨ Merge main back to develop    
      uses: everlytic/branch-merge@1.1.0
      if: steps.version_type.outputs.type != 'skip'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_ref: 'main'
        target_branch: 'develop'
        commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'

    - name: ðŸš€ Tag and Release
      uses: pypeclub/semver-release-action@master
      if: steps.version_type.outputs.type != 'skip'
      with:
        prefix: nightly/
        bump: ${{ steps.next_version.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.git_commit.outputs.sha }}