name: version_up

on:
  push:
    branches: [main]


jobs:
  Ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - name: üöõ Checkout Code
      uses: actions/checkout@v2

    - name: üÜô Find next version
      id: next_version
      uses: pypeclub/semver-release-action@master
      with:
        prefix: nightly/
        dry_run: true
        bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # Do something to modify the repo using `${{ steps.next_version.outputs.version }}`.

    - name: ‚úç Update version.py
      id: update_version
      run: |
        echo "${{ steps.next_version.outputs.version }}"

        python_version_regex="(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?"
        sed -i -E "s/$python_version_regex/${{ steps.next_version.outputs.version }}/g" ./openpypeCItest/version.py
        
        pyproject_version_regex="version \= \"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?\" \# OpenPype"
        sed -i -E "s/$pyproject_version_regex/version \= \"${{ steps.next_version.outputs.version }}\" \# OpenPype/g" ./pyproject.toml

    - name: üíæ Commit changes
      id: git_commit
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "Bump version"
        git push
        
        echo ::set-output name=sha::$(git rev-parse HEAD)

    - uses: everlytic/branch-merge@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_ref: 'main'
        target_branch: 'develop'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

    - name: üöÄ Tag and Release
      uses: pypeclub/semver-release-action@master
      with:
        prefix: nightly/
        bump: ${{ steps.next_version.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.git_commit.outputs.sha }}