name: version_up

on:
  push:
    branches: [main]


jobs:
  Ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - name: ğŸš› Checkout Code
      uses: actions/checkout@v2

    - name: ğŸ†™ Find next version
      id: next_version
      uses: zwaldowski/semver-release-action@v2
      with:
        prefix: nightly/
        dry_run: true
        bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # Do something to modify the repo using `${{ steps.next_version.outputs.version }}`.

    - name: âœ Update version.py
      id: update_version
      run: |
        echo "${{ steps.next_version.outputs.version }}"
        version_regex="(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?"
        sed -i -E "s/$version_regex/${{ steps.next_version.outputs.version }}/g" ./openpypeCItest/version.py
    
    - name: ğŸ’¾ Commit changes
      id: git_commit
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "Bump version"
        git push
        
        echo ::set-output name=sha::$(git rev-parse HEAD)
        
    - name: ğŸš€ Tag and Release
      uses: zwaldowski/semver-release-action@v2
      with:
        prefix: nightly/
        bump: ${{ steps.next_version.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.git_commit.outputs.sha }}